package pt.ipleiria.notepadv2.model;

import android.content.Context;
import android.os.Environment;

import com.google.android.gms.maps.model.LatLng;

import pt.ipleiria.notepadv2.MainActivity;

public interface AppConstants {

    String SAVE_FILE_NAME = "notepad.dat";
    String INTENT_EXTRA_NOTE = "note";
    int MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE = 99;
    int MY_PERMISSIONS_REQUEST_FINE_LOCATION = 100;
    int MY_PERMISSIONS_REQUEST_FINE_LOCATION_SETTINGS = 101;
    int MY_PERMISSIONS_REQUEST_FINE_LOCATION_REGISTER_FENCE = 102;
    int MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE_IMPORT_FILE = 103;
    int MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE_EXPORT_FILE = 104;
    int MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE_TAKE_PICTURE = 105;

    int REQUEST_CODE_PICK_CSV_FILE = 1000;

    int REQUEST_IMAGE_CAPTURE = 1;
    int REQUEST_IMAGE_GALLERY = 2;
    int REQUEST_VIDEO_CAPTURE = 3;
    int REQUEST_VIDEO_GALLERY = 4;
    int REQUEST_MAPS_COORDINATES = 5;
    int REQUEST_IMAGE_CAPTURE_CLOUD_VISION = 6;
    int REQUEST_IMAGE_GALLERY_CLOUD_VISION = 7;
    int REQUEST_ENABLE_BLUETOOTH = 8;

    //App TAGs
    String TAG_FENCE_RECEIVER = "Fence Receiver";
    String TAG_GETTING_CONTEXT = "Getting Context";
    String TAG_REQUEST_PERMISSION_RESULT = "Request Permission";
    String TAG_FENCE_REGIST = "Fence Registration";
    String TAG_GENERAL = "General";
    String TAG_REVERSE_GEOCODE = "Reverse Geocode";
    String TAG_PICK_FIlE_NO_HANDLER = "No Handler to File Pick";
    String TAG_CLOUD_VISION = "Cloud Vision";
    String TAG_BLUETOOTH = "Bluetooth";

    //Fences Keys
    String FENCE_RECEIVER_ACTION = "FENCE_RECEIVER_ACTION";

    String FENCE_KEY_HEADPHONES_HEADER = "headphonesFenceKey_";
    String FENCE_KEY_HEADPHONES_PLUGGING = FENCE_KEY_HEADPHONES_HEADER+"PLUGGING";
    String FENCE_KEY_HEADPHONES_UNPLUGGING = FENCE_KEY_HEADPHONES_HEADER+"UNPLUGGING";

    String FENCE_KEY_LOCATION = "locationFenceKey_";

    String[] AVAILABLE_ACTIVITY_TYPES = {"In Vehicle", "On Bicycle", "On Foot", "Running", "Still", "Tilting", "Walking"};
    String FENCE_KEY_ACTIVITY_HEADER = "activityFenceKey_";
    String FENCE_KEY_ACTIVITY_IN_VEHICLE = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[0];
    String FENCE_KEY_ACTIVITY_ON_BICYCLE = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[1];
    String FENCE_KEY_ACTIVITY_ON_FOOT = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[2];
    String FENCE_KEY_ACTIVITY_RUNNING = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[3];
    String FENCE_KEY_ACTIVITY_STILL = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[4];
    //Tilting Fence doesn't exist
    //String FENCE_KEY_ACTIVITY_TILTING = FENCE_KEY_ACTIVITY_HEADER++AVAILABLE_ACTIVITY_TYPES[5];
    String FENCE_KEY_ACTIVITY_WALKING = FENCE_KEY_ACTIVITY_HEADER+AVAILABLE_ACTIVITY_TYPES[6];


    String[] AVAILABLE_TIME_INTERVALS = {"TIME_INTERVAL_WEEKDAY","TIME_INTERVAL_WEEKEND","TIME_INTERVAL_HOLIDAY",
            "TIME_INTERVAL_MORNING","TIME_INTERVAL_AFTERNOON","TIME_INTERVAL_EVENING","TIME_INTERVAL_NIGHT"};
    int TIME_INTERVAL_LENGHT = 14; //TIME_INTERVAL_

    String FENCE_KEY_TIME_INTERVAL_HEADER = "timeIntervalFenceKey_";
    String FENCE_KEY_TIME_INTERVAL_WEEKDAY = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[0];
    String FENCE_KEY_TIME_INTERVAL_WEEKEND = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[1];
    String FENCE_KEY_TIME_INTERVAL_HOLIDAY = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[2];
    String FENCE_KEY_TIME_INTERVAL_MORNING = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[3];
    String FENCE_KEY_TIME_INTERVAL_AFTERNOON = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[4];
    String FENCE_KEY_TIME_INTERVAL_EVENING = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[5];
    String FENCE_KEY_TIME_INTERVAL_NIGHT = FENCE_KEY_TIME_INTERVAL_HEADER + AVAILABLE_TIME_INTERVALS[6];
    /**
     * Keywords Snapshot Filter Types
     *  #headphones:PLUGGED_IN / #headphones:UNPLUGGED
     *  #temperature:[Operator][Value] //TODO: Done [Temp Unit]
     *  #humidity: [Operator][Value]
     *  #weather: [CONDITION] ex.: Weather.CONDITION_CLEAR
     *  #location: [Value LAT], [Value LONG], [OPTIONAL Value RADIUS]
     *  #activity: [ACTIVITY CONSTANT]
     *  #place: [PLACE TYPE CONSTANT]
     *  #time: [TIME INTERVAL]
     */
    float NUMBER_OF_TASKS_AWARENESS_API = 6;
    char FILTER_KEYWORD_MARKER = '#';
    char FILTER_KEYWORD_SEPARATOR = ':';
    String[] AVAILABLE_FILTERS = {"headphones", "temperature", "humidity", "weather", "location", "activity", "place", "time"};
    String[] AVAILABLE_HEADPHONES_TYPES = {"Plugged In", "Unplugged"};
    String[] AVAILABLE_WEATHER_TYPES = {"Clear", "Cloudy","Foggy", "Hazy", "Icy", "Rainy", "Snowy", "Stormy", "Windy"};
    //Defined Above
    // String[] AVAILABLE_ACTIVITY_TYPES = {"In Vehicle", "On Bicycle", "On Foot", "Running", "Still", "Tilting", "Walking"};
    String[] ALL_PLACES_TYPES = {"OTHER","ACCOUNTING","AIRPORT","AMUSEMENT_PARK","AQUARIUM","ART_GALLERY","ATM","BAKERY","BANK","BAR","BEAUTY_SALON","BICYCLE_STORE","BOOK_STORE","BOWLING_ALLEY","BUS_STATION","CAFE","CAMPGROUND","CAR_DEALER","CAR_RENTAL","CAR_REPAIR","CAR_WASH","CASINO","CEMETERY","CHURCH","CITY_HALL","CLOTHING_STORE","CONVENIENCE_STORE","COURTHOUSE","DENTIST","DEPARTMENT_STORE","DOCTOR","ELECTRICIAN","ELECTRONICS_STORE","EMBASSY","ESTABLISHMENT","FINANCE","FIRE_STATION","FLORIST","FOOD","FUNERAL_HOME","FURNITURE_STORE","GAS_STATION","GENERAL_CONTRACTOR","GROCERY_OR_SUPERMARKET","GYM","HAIR_CARE","HARDWARE_STORE","HEALTH","HINDU_TEMPLE","HOME_GOODS_STORE","HOSPITAL","INSURANCE_AGENCY","JEWELRY_STORE","LAUNDRY","LAWYER","LIBRARY","LIQUOR_STORE","LOCAL_GOVERNMENT_OFFICE","LOCKSMITH","LODGING","MEAL_DELIVERY","MEAL_TAKEAWAY","MOSQUE","MOVIE_RENTAL","MOVIE_THEATER","MOVING_COMPANY","MUSEUM","NIGHT_CLUB","PAINTER","PARK","PARKING","PET_STORE","PHARMACY","PHYSIOTHERAPIST","PLACE_OF_WORSHIP","PLUMBER","POLICE","POST_OFFICE","REAL_ESTATE_AGENCY","RESTAURANT","ROOFING_CONTRACTOR","RV_PARK","SCHOOL","SHOE_STORE","SHOPPING_MALL","SPA","STADIUM","STORAGE","STORE","SUBWAY_STATION","SYNAGOGUE","TAXI_STAND","TRAIN_STATION","TRAVEL_AGENCY","UNIVERSITY","VETERINARY_CARE","ZOO","ADMINISTRATIVE_AREA_LEVEL_1","ADMINISTRATIVE_AREA_LEVEL_2","ADMINISTRATIVE_AREA_LEVEL_3","COLLOQUIAL_AREA","COUNTRY","FLOOR","GEOCODE","INTERSECTION","LOCALITY","NATURAL_FEATURE","NEIGHBORHOOD","POLITICAL","POINT_OF_INTEREST","POST_BOX","POSTAL_CODE","POSTAL_CODE_PREFIX","POSTAL_TOWN","PREMISE","ROOM","ROUTE","STREET_ADDRESS","SUBLOCALITY","SUBLOCALITY_LEVEL_1","SUBLOCALITY_LEVEL_2","SUBLOCALITY_LEVEL_3","SUBLOCALITY_LEVEL_4","SUBLOCALITY_LEVEL_5","SUBPREMISE","SYNTHETIC_GEOCODE","TRANSIT_STATION"};
    //Defined Above
    // String[] AVAILABLE_TIME_INTERVALS = {"TIME_INTERVAL_WEEKDAY" ,"TIME_INTERVAL_WEEKEND" ,"TIME_INTERVAL_HOLIDAY" ,"TIME_INTERVAL_MORNING" ,"TIME_INTERVAL_AFTERNOON" ,"TIME_INTERVAL_EVENING" ,"TIME_INTERVAL_NIGHT"};

    //TO MAKE EASIER CODDING
    String HEADPHONES = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[0]+FILTER_KEYWORD_SEPARATOR;
    String TEMPERATURE = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[1]+FILTER_KEYWORD_SEPARATOR;
    String HUMIDITY = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[2]+FILTER_KEYWORD_SEPARATOR;
    String WEATHER_CONDITION = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[3]+FILTER_KEYWORD_SEPARATOR;
    String LOCATION = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[4]+FILTER_KEYWORD_SEPARATOR;
    String ACTIVITY = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[5]+FILTER_KEYWORD_SEPARATOR;
    String PLACE_TYPE = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[6]+FILTER_KEYWORD_SEPARATOR;
    String TIME_INTERVAL = FILTER_KEYWORD_MARKER+AVAILABLE_FILTERS[7]+FILTER_KEYWORD_SEPARATOR;
    int NEARBY_PLACES_SHOW_SIZE = 3;
    double NEARBY_PLACES_MINIMUM_LIKELIHOOD = 0.3;

    //Preferences
    String PREFERENCE_FILE_KEY = "pt.ipleiria.notepadv2.PREFERENCE_FILE_KEY";
    String PREFS_LOCATION_RADIUS_KEY = "sharedPrefsLocationRadius";
    int LOCATION_DEFAULT_RADIUS = 100; //Default search radius in meters
    String PREFS_DWELL_TIME_KEY = "sharedPrefsDwellTime";
    int DWELL_DEFAULT_TIME = 1; //Default search radius in meters
    String PREFS_TEMPERATURE_UNIT_KEY = "sharedPrefsTemperatureUnit";
    String[] AVAILABLE_TEMPERATURE_UNITS = {"CELSIUS", "FAHRENHEIT"};
    String HEADPHONE_FENCE_STATE = "headphonesFenceState";
    String LOCATION_FENCE_STATE = "locationFenceState";
    String ACTIVITY_FENCE_STATE = "activityFenceState";
    String TIME_FENCE_STATE = "timeFenceState";

    LatLng DEFAULT_LOCATION = new LatLng(39.7541724,-8.8759985);

    String EXPORT_FILE_FOLDER = Environment.DIRECTORY_DOWNLOADS;
    String[] IMPORT_NOTES_FIELDS_TYPES = {"TITLE", "KEYWORDS", "BODY_TEXT"};
    String NEW_LINE_EXPORT_FILE = "¶";
    String NEW_FIELD_EXPORT_FILE = "ʻ";
    String NEW_NOTE_EXPORT_FILE = "§";

    //CloudVision
    String CLOUD_VISION_API_KEY = "AIzaSyD5SmAlLZdH8Fr-hnTDuUcjN_hDcczDEXM";
    String ANDROID_CERT_HEADER = "X-Android-Cert";
    String ANDROID_PACKAGE_HEADER = "X-Android-Package";
    int RESIZE_IMAGE_TO_MAX_DIMENSIONS = 1024;
    double MIN_CLOUD_VISION_LABEL_SCORE = 0.7;
    double MIN_CLOUD_VISION_LANDMARK_SCORE = 0.5;
    double MIN_CLOUD_VISION_LOGO_SCORE = 0.5;
    double MIN_CLOUD_VISION_WEB_ENTITY_SCORE = 0.5;

}
